Repository department-of-veterans-affairs/va.gov-team, pull requests merged in 2025-04, with the labels that each got.

#107472 Create Evidence Request "Friendly Language" Initiative.md
  products/claim-appeal-status/CST Product/Evidence Request "Friendly Language" Initiative.md
Labels: bmt-team-2

#107605 Benefit Summary logic documentation, first commit.
  products/benefit-letters/discovery/benefit_summary_logic.md
Labels: documentation, Letters and documents, benefits-management-tools, bmt-team-2

#108720 [TASK]: Add voice command to accessibility template options
  .github/ISSUE_TEMPLATE/a11y-issue.yaml
Labels: documentation, accessibility
